name: Chromatic - UI Storybook

on:
  push:
    branches:
      - dev
    paths:
      - 'packages/ui/tailwind/**'

env:
  DEFAULT_NODE_VERSION: '20.11.0'
  PNPM_VERSION: '9.0.6'

jobs:
  chromatic:
    name: Publish Storybook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: packages/ui/tailwind
          exitOnceUploaded: true
