name: 'Pull Request Labeler'

on:
  pull_request:
    branches:
      - '**'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: srvaroa/labeler@master
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
